### ISSUE TITLE
Python kernel error (in Binder): PYJNIUS_JAR environment variable not defined.

### ISSUE THREAD

**Issue by nicost** [imagej/tutorials#62]
When running the ImageJ-with-Python kernel in Binder, executing the first cell results in:

ERROR 2019-01-02 23:03:02,049: Unable to import scyjava: PYJNIUS_JAR environment variable not defined.

Is this a problem with my environment, the environment on the Binder server, or something else entirely?

What do I need to do to run this kernel on my local machine?

**Comment by ctrueden** [comment]
Same instructions in the README should also enable the Python notebook locally. Give it a try and paste any errors here.

I will investigate the Binder failure. Probably will be solved by addressing imagej/pyimagej#21 and scijava/scyjava#5.

**Comment by nicost** [comment]
Which README?  I don't see instructions here: https://github.com/imagej/tutorials/blob/master/README.md.  I really must be missing something very obvious.

Cloning the repository, installing Jupyter, and running "jupyter notebook" from within the "notebooks" directory results in a similar error (see below).  Note that I do have pyjnius installed:

valenico:1-Using-ImageJ nico$ pip3 list | grep jnius
jnius              1.1.0     
pyjnius            1.1.4



ERROR 2019-01-02 16:59:24,849: Unable to import scyjava: PYJNIUS_JAR environment variable not defined.

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-42b6b562a3b2> in <module>()
      1 import imagej
----> 2 ij = imagej.init('sc.fiji:fiji:2.0.0-pre-10')
      3 ij.getVersion()

/usr/local/lib/python3.7/site-packages/imagej/imagej.py in init(ij_dir_or_version_or_endpoint, headless)
    102 
    103     # Must import imglyb (not scyjava) to spin up the JVM now.
--> 104     import imglyb
    105     from jnius import autoclass
    106 

/usr/local/lib/python3.7/site-packages/imglyb/__init__.py in <module>()
     39 
     40 
---> 41 config, _ = _init_jvm_options()
     42 
     43 from .imglib_ndarray import ImgLibReferenceGuard as _ImgLibReferenceGuard

/usr/local/lib/python3.7/site-packages/imglyb/__init__.py in _init_jvm_options()
     34     scyjava_config.add_endpoints(IMGLIB2_IMGLYB_ENDPOINT)
     35 
---> 36     import scyjava
     37 
     38     return jnius_config, scyjava

/usr/local/lib/python3.7/site-packages/scyjava/__init__.py in <module>()
     55 jnius = _init_jvm()
     56 if (jnius == None):
---> 57     raise ImportError('Unable to import scyjava dependency jnius.')
     58 
     59 from .convert import isjava, jclass, to_java, to_python

ImportError: Unable to import scyjava dependency jnius.

**Comment by ctrueden** [comment]
> Which README? I don't see instructions

The instructions I committed with c2e454bd759d85925157fdf11a254c2053ebbdee.

> Cloning the repository, installing Jupyter, and running "jupyter notebook" from within the "notebooks" directory results in a similar error (see below).

Are you using conda? Did you `source activate` the environment first? Unfortunately, right now, you have to activate the environment because it runs a couple of activation scripts that set those environment variables properly. As part of fixing imagej/pyimagej#21 and scijava/scyjava#5, I hope to eliminate that requirement, so that it is sufficient to use the Python within a particular environment _without_ activating it. There are other use cases like Binder and https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets/issues/116#issuecomment-445271955 that will be fulfilled by doing that.

**Comment by nicost** [comment]
Thanks!  Following these instructions to the letter worked.  I as a bit scared to add yet another package manager that I don't understand to the mix, but it seems to do its thing well.  The notebook indeed runs as it should.

**Comment by ctrueden** [comment]
@nicost Glad to hear it is working!

**Comment by imagejan** [comment]
When running on binder, I still get the same error message in the `6-ImageJ-with-Python-kernel` notebook upon trying to run the first code cell:

```
ERROR 2019-01-09 20:47:48,370: Unable to import scyjava: PYJNIUS_JAR environment variable not defined.
```

**Comment by ctrueden** [comment]
Thanks @imagejan. I think this specific issue will be resolved by fixing scijava/scyjava#5. @gselzer is currently working on it now. But we can leave this issue open as a blanket issue indicating that the Python-based ImageJ notebook does not currently work on Binder.

**Comment by ctrueden** [comment]
With the release of scyjava 0.2.2, I was hoping this issue would be solved.

However, spinning up Binder yields the following error:
```
LinkError: post-link script failed for package conda-forge::beakerx-1.4.0-py37_0
running your command again with `-v` will provide additional information
location of failed script: /srv/conda/bin/.beakerx-post-link.sh
==> script messages <==
+ /srv/conda/bin/beakerx install
Traceback (most recent call last):
  File "/srv/conda/bin/beakerx", line 7, in <module>
    from beakerx import run
  File "/srv/conda/lib/python3.7/site-packages/beakerx/__init__.py", line 15, in <module>
    from .plot import *
  File "/srv/conda/lib/python3.7/site-packages/beakerx/plot/__init__.py", line 15, in <module>
    from .chart import *
  File "/srv/conda/lib/python3.7/site-packages/beakerx/plot/chart.py", line 17, in <module>
    from pandas import DataFrame
  File "/srv/conda/lib/python3.7/site-packages/pandas/__init__.py", line 19, in <module>
    "Missing required dependencies {0}".format(missing_dependencies))
ImportError: Missing required dependencies ['numpy']
```

I got the error with beakerx 1.4.1, and thought that downgrading to 1.4.0 would work (it works locally for me), so I tried it with 95dc6b0bfb22b215f71333ebf3863c0ae0eaf29e. But the problem persists. 😔 This issue is already reported upstream at twosigma/beakerx#8022, but no response yet.

**Comment by imagejan** [comment]
@ctrueden moving the `beakerx` installation from `environment.yml` to `postBuild` fixed the issue when running on mybinder.org:

https://github.com/imagej/tutorials/compare/master...imagejan:imagejan-test-python-3.6

(I also tried pinning to Python 3.6 and removing `jupyter_contrib_nbextensions` before, which didn't fix it, but this is now possibly not required any more.)

I was now able to run the python notebook (`6-ImageJ-with-Python-kernel`) on binder without errors 🎉 :
https://mybinder.org/v2/gh/imagejan/imagej-tutorials/imagejan-test-python-3.6

**Comment by ctrueden** [comment]
Fixed by #71.
